# -*- coding: utf-8 -*-
# author：童颖睿

# Form implementation generated from reading ui file 'LeftSingleBlock.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication
from PyQt5.QtCore import Qt
import requests

class Ui_BrandBlock(QtWidgets.QWidget):
    def __init__(self, oneCarList):  # 传一辆车的参数，一个list
        super(Ui_BrandBlock, self).__init__()
        self.oneCarList = oneCarList
        self.setupUi()

    def setupUi(self):

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sizePolicy().hasHeightForWidth())
        self.setSizePolicy(sizePolicy)

        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")

        # 图标
        self.carImg = QtWidgets.QLabel()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.carImg.sizePolicy().hasHeightForWidth())
        self.carImg.setSizePolicy(sizePolicy)
        self.carImg.setObjectName("carImg")

        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")

        #车名
        self.carName = QtWidgets.QLabel()
        self.carName.setObjectName("carName")
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.carName.setFont(font)
        self.carName.setAlignment(Qt.AlignCenter)

        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)

        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)

        #new
        self.verticalLayout_3.addWidget(self.carImg)
        self.verticalLayout_3.addItem(spacerItem1)
        self.verticalLayout_3.addWidget(self.carName)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_3.addItem(spacerItem2)

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)

        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")

        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)

        self.retranslateUi()

        self.setLayout(self.verticalLayout_2)

    def retranslateUi(self):
        #显示车标
        self.carImg.setText("【车标图片】")
        img = QtGui.QPixmap("./carImg/" + str(self.oneCarList[0]) + ".png").scaled(QtCore.QSize(150, 120))
        self.carImg.setPixmap(img)

        self.carName.setText("TextLabel")
        self.carName.setText(self.oneCarList[0])  # 车名

        # url = self.oneCarList[1]  # 车图片
        # req = requests.get(url)
        # carPhoto = QtGui.QPixmap()
        # carPhoto.loadFromData(req.content)
        # carPhoto = carPhoto.scaled(QtCore.QSize(160, 120))  # 4:3
        # self.carImg.setPixmap(carPhoto)


if __name__ == '__main__':
    QApplication.setAttribute(Qt.AA_EnableHighDpiScaling)
    app = QtWidgets.QApplication(sys.argv)
    ex = Ui_BrandBlock(['BMW'])
    ex.show()
    sys.exit(app.exec_())