# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'index.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
# author：车诗琪

from PyQt5 import QtCore, QtGui, QtWidgets
import pic_rc


class Ui_index(object):
    def setupUi(self, index):
        index.setObjectName("index")
        index.resize(523, 307)
        self.label = QtWidgets.QLabel(index)
        self.label.setGeometry(QtCore.QRect(-30, 0, 561, 311))
        self.label.setStyleSheet("border-image: url(:/new/prefix1/pyqtpic/indexback.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.logoRecognition = QtWidgets.QPushButton(index)
        self.logoRecognition.setGeometry(QtCore.QRect(310, 60, 181, 51))
        self.logoRecognition.setStyleSheet("QPushButton\n"
"{\n"
"    border-image: url(:/new/prefix1/pyqtpic/carreg.png);\n"
"    color:transparnt;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    border-image: url(:/new/prefix1/pyqtpic/carreg-1.png);\n"
"    color:transparnt;\n"
"}")
        self.logoRecognition.setText("")
        self.logoRecognition.setObjectName("logoRecognition")
        self.home = QtWidgets.QPushButton(index)
        self.home.setGeometry(QtCore.QRect(310, 130, 181, 51))
        self.home.setStyleSheet("QPushButton\n"
"{\n"
"    border-image: url(:/new/prefix1/pyqtpic/home.png);\n"
"    color:transparnt;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    border-image: url(:/new/prefix1/pyqtpic/home-1.png);\n"
"    color:transparnt;\n"
"}")
        self.home.setText("")
        self.home.setObjectName("home")
        self.carLogo = QtWidgets.QPushButton(index)
        self.carLogo.setGeometry(QtCore.QRect(310, 200, 181, 51))
        self.carLogo.setStyleSheet("QPushButton\n"
"{\n"
"    border-image: url(:/new/prefix1/pyqtpic/carlogo.png);\n"
"    color:transparnt;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    border-image: url(:/new/prefix1/pyqtpic/carlogo-1.png);\n"
"    color:transparnt;\n"
"}")
        self.carLogo.setText("")
        self.carLogo.setObjectName("carLogo")

        self.retranslateUi(index)
        QtCore.QMetaObject.connectSlotsByName(index)

    def retranslateUi(self, index):
        _translate = QtCore.QCoreApplication.translate
        index.setWindowTitle(_translate("index", "Form"))
