# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
# author：车诗琪

from PyQt5 import QtCore, QtGui, QtWidgets
import pic_rc


class Ui_login(object):
    def setupUi(self, login):
        login.setObjectName("login")
        login.resize(570, 355)
        self.centralwidget = QtWidgets.QWidget(login)
        self.centralwidget.setObjectName("centralwidget")
        self.logbackground = QtWidgets.QLabel(self.centralwidget)
        self.logbackground.setGeometry(QtCore.QRect(0, 0, 571, 331))
        self.logbackground.setStyleSheet("border-image: url(:/new/prefix1/pyqtpic/logback.png);")
        self.logbackground.setText("")
        self.logbackground.setObjectName("logbackground")
        self.logIn = QtWidgets.QPushButton(self.centralwidget)
        self.logIn.setGeometry(QtCore.QRect(330, 170, 71, 31))
        self.logIn.setStyleSheet("QPushButton\n"
"{\n"
"    border-image: url(:/new/prefix1/pyqtpic/signin.png);\n"
"    color:transparnt;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    border-image: url(:/new/prefix1/pyqtpic/signin-1.png);\n"
"    color:transparnt;\n"
"}")
        self.logIn.setText("")
        self.logIn.setAutoRepeatDelay(300)
        self.logIn.setObjectName("logIn")
        self.cancel = QtWidgets.QPushButton(self.centralwidget)
        self.cancel.setGeometry(QtCore.QRect(420, 170, 71, 31))
        self.cancel.setStyleSheet("QPushButton\n"
"{\n"
"    border-image: url(:/new/prefix1/pyqtpic/cancel.png);\n"
"    color:transparnt;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    border-image: url(:/new/prefix1/pyqtpic/cancel-1.png);\n"
"    color:transparnt;\n"
"}")
        self.cancel.setText("")
        self.cancel.setObjectName("cancel")
        self.lineEdit_account = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_account.setGeometry(QtCore.QRect(373, 87, 113, 27))
        self.lineEdit_account.setObjectName("lineEdit_account")
        self.lineEdit_password = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_password.setGeometry(QtCore.QRect(373, 125, 113, 27))
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(340, 220, 91, 16))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.register_2 = QtWidgets.QPushButton(self.centralwidget)
        self.register_2.setGeometry(QtCore.QRect(416, 214, 93, 28))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.register_2.setFont(font)
        self.register_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.register_2.setFlat(True)
        self.register_2.setObjectName("register_2")
        login.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(login)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 570, 26))
        self.menubar.setObjectName("menubar")
        login.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(login)
        self.statusbar.setObjectName("statusbar")
        login.setStatusBar(self.statusbar)

        self.retranslateUi(login)
        QtCore.QMetaObject.connectSlotsByName(login)

    def retranslateUi(self, login):
        _translate = QtCore.QCoreApplication.translate
        login.setWindowTitle(_translate("login", "车标识别系统"))
        self.label.setText(_translate("login", "还没有账号？"))
        self.register_2.setText(_translate("login", "点击注册"))
