# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Recognizing.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Recognizing(object):
    def setupUi(self, Recognizing):
        Recognizing.setObjectName("Recognizing")
        Recognizing.resize(661, 441)
        self.layoutWidget = QtWidgets.QWidget(Recognizing)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 386, 22))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.return_2 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(12)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.return_2.sizePolicy().hasHeightForWidth())
        self.return_2.setSizePolicy(sizePolicy)
        self.return_2.setMaximumSize(QtCore.QSize(30, 20))
        self.return_2.setObjectName("return_2")
        self.horizontalLayout_2.addWidget(self.return_2)
        spacerItem = QtWidgets.QSpacerItem(348, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.widget = QtWidgets.QWidget(Recognizing)
        self.widget.setGeometry(QtCore.QRect(10, 40, 337, 252))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(250)
        sizePolicy.setVerticalStretch(200)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(250, 200))
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.select = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.select.sizePolicy().hasHeightForWidth())
        self.select.setSizePolicy(sizePolicy)
        self.select.setMaximumSize(QtCore.QSize(256, 16777215))
        self.select.setObjectName("select")
        self.verticalLayout.addWidget(self.select)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.recognize = QtWidgets.QPushButton(self.widget)
        self.recognize.setObjectName("recognize")
        self.verticalLayout_2.addWidget(self.recognize)
        spacerItem2 = QtWidgets.QSpacerItem(20, 208, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(Recognizing)
        QtCore.QMetaObject.connectSlotsByName(Recognizing)

    def retranslateUi(self, Recognizing):
        _translate = QtCore.QCoreApplication.translate
        Recognizing.setWindowTitle(_translate("Recognizing", "Recognizing"))
        self.return_2.setText(_translate("Recognizing", "<"))
        self.select.setText(_translate("Recognizing", "Select"))
        self.recognize.setText(_translate("Recognizing", "Recognize"))


