# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Recognizing2.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Recognizing2(object):
    def setupUi(self, Recognizing2):
        Recognizing2.setObjectName("Recognizing2")
        Recognizing2.resize(661, 441)
        self.pic = QtWidgets.QLabel(Recognizing2)
        self.pic.setGeometry(QtCore.QRect(500, 20, 131, 121))
        self.pic.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);")
        self.pic.setText("")
        self.pic.setObjectName("pic")
        self.name = QtWidgets.QLabel(Recognizing2)
        self.name.setGeometry(QtCore.QRect(530, 160, 71, 21))
        self.name.setStyleSheet("background-color: rgb(255, 255, 189);")
        self.name.setText("")
        self.name.setAlignment(QtCore.Qt.AlignCenter)
        self.name.setObjectName("name")
        self.iLike = QtWidgets.QPushButton(Recognizing2)
        self.iLike.setGeometry(QtCore.QRect(530, 190, 75, 23))
        self.iLike.setStyleSheet("background-color: rgb(255, 167, 255);")
        self.iLike.setObjectName("iLike")
        self.scrollArea = QtWidgets.QScrollArea(Recognizing2)
        self.scrollArea.setGeometry(QtCore.QRect(10, 330, 641, 101))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setEnabled(False)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 622, 280))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 280))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.briefIntro = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.briefIntro.setGeometry(QtCore.QRect(0, 0, 621, 271))
        self.briefIntro.setText("")
        self.briefIntro.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.briefIntro.setWordWrap(True)
        self.briefIntro.setObjectName("briefIntro")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.back = QtWidgets.QPushButton(Recognizing2)
        self.back.setGeometry(QtCore.QRect(10, 10, 31, 23))
        self.back.setObjectName("back")
        self.likeShow = QtWidgets.QLabel(Recognizing2)
        self.likeShow.setGeometry(QtCore.QRect(500, 230, 131, 31))
        self.likeShow.setStyleSheet("font: 11pt \"Arial\";")
        self.likeShow.setText("")
        self.likeShow.setAlignment(QtCore.Qt.AlignCenter)
        self.likeShow.setObjectName("likeShow")

        self.retranslateUi(Recognizing2)
        QtCore.QMetaObject.connectSlotsByName(Recognizing2)

    def retranslateUi(self, Recognizing2):
        _translate = QtCore.QCoreApplication.translate
        Recognizing2.setWindowTitle(_translate("Recognizing2", "Recognizing2"))
        self.iLike.setText(_translate("Recognizing2", "ILIKE"))
        self.back.setText(_translate("Recognizing2", "<"))
