# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Recognizing.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Recognizing(object):
    def setupUi(self, Recognizing):
        Recognizing.setObjectName("Recognizing")
        Recognizing.resize(661, 441)
        Recognizing.setStyleSheet("#frame{border-image: url(:/pyqtpic/recog.jpg);}")
        self.frame = QtWidgets.QFrame(Recognizing)
        self.frame.setGeometry(QtCore.QRect(0, 0, 661, 441))
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.recognize = QtWidgets.QPushButton(self.frame)
        self.recognize.setGeometry(QtCore.QRect(540, 380, 75, 23))
        self.recognize.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.recognize.setObjectName("recognize")
        self.select = QtWidgets.QPushButton(self.frame)
        self.select.setGeometry(QtCore.QRect(290, 370, 75, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.select.sizePolicy().hasHeightForWidth())
        self.select.setSizePolicy(sizePolicy)
        self.select.setMaximumSize(QtCore.QSize(256, 16777215))
        self.select.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.select.setObjectName("select")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(143, 60, 371, 281))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(250)
        sizePolicy.setVerticalStretch(200)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(250, 200))
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-bottom-color: rgb(46, 126, 135);")
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setText("")
        self.label.setObjectName("label")
        self.return_2 = QtWidgets.QPushButton(self.frame)
        self.return_2.setGeometry(QtCore.QRect(10, 18, 30, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(12)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.return_2.sizePolicy().hasHeightForWidth())
        self.return_2.setSizePolicy(sizePolicy)
        self.return_2.setMaximumSize(QtCore.QSize(30, 20))
        self.return_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.return_2.setObjectName("return_2")
        self.time = QtWidgets.QLabel(self.frame)
        self.time.setGeometry(QtCore.QRect(13, 60, 115, 78))
        self.time.setStyleSheet("background-color: rgb(46, 126, 135);\n"
"font: 16pt \"Arial\";\n"
"color: rgb(255, 255, 255);")
        self.time.setText("")
        self.time.setAlignment(QtCore.Qt.AlignCenter)
        self.time.setObjectName("time")
        self.date = QtWidgets.QLabel(self.frame)
        self.date.setGeometry(QtCore.QRect(17, 148, 91, 16))
        self.date.setStyleSheet("background-color: rgb(46, 126, 135);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"Arial\";")
        self.date.setText("")
        self.date.setAlignment(QtCore.Qt.AlignCenter)
        self.date.setObjectName("date")

        self.retranslateUi(Recognizing)
        QtCore.QMetaObject.connectSlotsByName(Recognizing)

    def retranslateUi(self, Recognizing):
        _translate = QtCore.QCoreApplication.translate
        Recognizing.setWindowTitle(_translate("Recognizing", "车标识别"))
        self.recognize.setText(_translate("Recognizing", "Recognize"))
        self.select.setText(_translate("Recognizing", "Select"))
        self.return_2.setText(_translate("Recognizing", "<"))
import Recog_rc
