# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Recognizing2.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Recognizing2(object):
    def setupUi(self, Recognizing2):
        Recognizing2.setObjectName("Recognizing2")
        Recognizing2.resize(684, 441)
        self.pic = QtWidgets.QLabel(Recognizing2)
        self.pic.setGeometry(QtCore.QRect(480, 10, 61, 61))
        self.pic.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);")
        self.pic.setText("")
        self.pic.setObjectName("pic")
        self.name = QtWidgets.QLabel(Recognizing2)
        self.name.setGeometry(QtCore.QRect(550, 10, 131, 41))
        self.name.setStyleSheet("background-color: rgb(255, 255, 189);\n"
"font: 14pt \"Arial\";")
        self.name.setText("")
        self.name.setAlignment(QtCore.Qt.AlignCenter)
        self.name.setObjectName("name")
        self.iLike = QtWidgets.QPushButton(Recognizing2)
        self.iLike.setGeometry(QtCore.QRect(580, 60, 75, 23))
        self.iLike.setStyleSheet("background-color: rgb(255, 167, 255);")
        self.iLike.setObjectName("iLike")
        self.scrollArea = QtWidgets.QScrollArea(Recognizing2)
        self.scrollArea.setGeometry(QtCore.QRect(480, 130, 201, 301))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setEnabled(False)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -701, 182, 1000))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 1000))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.briefIntro = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.briefIntro.setGeometry(QtCore.QRect(0, 0, 201, 1000))
        self.briefIntro.setText("")
        self.briefIntro.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.briefIntro.setWordWrap(True)
        self.briefIntro.setObjectName("briefIntro")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.back = QtWidgets.QPushButton(Recognizing2)
        self.back.setGeometry(QtCore.QRect(10, 10, 31, 23))
        self.back.setObjectName("back")
        self.likeShow = QtWidgets.QLabel(Recognizing2)
        self.likeShow.setGeometry(QtCore.QRect(550, 90, 121, 31))
        self.likeShow.setStyleSheet("font: 11pt \"Arial\";")
        self.likeShow.setText("")
        self.likeShow.setAlignment(QtCore.Qt.AlignCenter)
        self.likeShow.setObjectName("likeShow")
        self.scrollArea_2 = QtWidgets.QScrollArea(Recognizing2)
        self.scrollArea_2.setGeometry(QtCore.QRect(10, 40, 461, 391))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        #self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 442, 3000))
        self.scrollAreaWidgetContents_2.setMinimumSize(QtCore.QSize(0, 3000))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        #self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 160, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)

        self.retranslateUi(Recognizing2)
        QtCore.QMetaObject.connectSlotsByName(Recognizing2)

    def retranslateUi(self, Recognizing2):
        _translate = QtCore.QCoreApplication.translate
        Recognizing2.setWindowTitle(_translate("Recognizing2", "Recognizing2"))
        self.iLike.setText(_translate("Recognizing2", "ILIKE"))
        self.back.setText(_translate("Recognizing2", "<"))
