# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'regist.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
# author：车诗琪


from PyQt5 import QtCore, QtGui, QtWidgets
import pic_rc


class Ui_regist(object):
    def setupUi(self, regist):
        regist.setObjectName("regist")
        regist.resize(535, 378)
        self.label = QtWidgets.QLabel(regist)
        self.label.setGeometry(QtCore.QRect(0, 0, 541, 381))
        self.label.setStyleSheet("border-image: url(:/new/prefix1/pyqtpic/rgst-back.jpg);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.lineEdit_account = QtWidgets.QLineEdit(regist)
        self.lineEdit_account.setGeometry(QtCore.QRect(220, 117, 151, 28))
        self.lineEdit_account.setObjectName("lineEdit_account")
        self.lineEdit_password = QtWidgets.QLineEdit(regist)
        self.lineEdit_password.setGeometry(QtCore.QRect(220, 163, 151, 28))
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.lineEdit_confirmpassword = QtWidgets.QLineEdit(regist)
        self.lineEdit_confirmpassword.setGeometry(QtCore.QRect(220, 211, 151, 28))
        self.lineEdit_confirmpassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_confirmpassword.setObjectName("lineEdit_confirmpassword")
        self.register_2 = QtWidgets.QPushButton(regist)
        self.register_2.setGeometry(QtCore.QRect(150, 270, 93, 41))
        self.register_2.setStyleSheet("QPushButton\n"
"{    \n"
"    border-image: url(:/new/prefix1/pyqtpic/register.png);\n"
"    color: transparents;\n"
"}\n"
"QPushButton:hover\n"
"{    \n"
"    border-image: url(:/new/prefix1/pyqtpic/register-1.png);\n"
"    color: transparents;\n"
"}")
        self.register_2.setText("")
        self.register_2.setObjectName("register_2")
        self.cancel = QtWidgets.QPushButton(regist)
        self.cancel.setGeometry(QtCore.QRect(290, 270, 93, 41))
        self.cancel.setStyleSheet("QPushButton\n"
"{    \n"
"    border-image: url(:/new/prefix1/pyqtpic/cancel.png);\n"
"    color: transparents;\n"
"}\n"
"QPushButton:hover\n"
"{    \n"
"    border-image: url(:/new/prefix1/pyqtpic/cancel-1.png);\n"
"    color: transparents;\n"
"}")
        self.cancel.setText("")
        self.cancel.setObjectName("cancel")
        self.tip_account = QtWidgets.QLabel(regist)
        self.tip_account.setGeometry(QtCore.QRect(222, 147, 141, 16))
        self.tip_account.setText("")
        self.tip_account.setObjectName("tip_account")
        self.tip_password = QtWidgets.QLabel(regist)
        self.tip_password.setGeometry(QtCore.QRect(222, 193, 141, 16))
        self.tip_password.setText("")
        self.tip_password.setObjectName("tip_password")
        self.tip_confirmpassword = QtWidgets.QLabel(regist)
        self.tip_confirmpassword.setGeometry(QtCore.QRect(222, 240, 141, 16))
        self.tip_confirmpassword.setText("")
        self.tip_confirmpassword.setObjectName("tip_confirmpassword")

        self.retranslateUi(regist)
        QtCore.QMetaObject.connectSlotsByName(regist)

    def retranslateUi(self, regist):
        _translate = QtCore.QCoreApplication.translate
        regist.setWindowTitle(_translate("regist", "注册账号"))
