# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'brandIntro.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'brandIntro.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QSize, Qt
from PyQt5.QtGui import QFont, QBrush, QColor
from PyQt5.QtWidgets import QApplication, QMainWindow, QDialog, QMessageBox, QAction, QTableWidgetItem, QLabel, \
    QHBoxLayout
import sys
import sqlite3
import requests


from car_spider import *


# 左边推荐表格+swf的品牌百度百科信息合并版
class Ui_BrandIntro(object):

    list = get_one_brand(1)
    def __init__(self, brandEname):  # 传入品牌英文名（识别结果）
        print("连接数据库...")
        self.conn = sqlite3.connect("database.db")  # 连接数据库
        print("连接成功...")
        self.cursor = self.conn.cursor()

        # 从数据库查询检测到的品牌
        sql = '''
            SELECT * from CAR_BRAND where cname = \"{ename}\"
        '''.format(ename=brandEname)
        print("查询品牌信息...")
        self.cursor.execute(sql)
        self.brandInfo = self.cursor.fetchone()  # 一行
        print("查询成功...")  # 得到tuple

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(981, 646)

        self.carLogo = QtWidgets.QLabel(Form)
        self.carLogo.setGeometry(QtCore.QRect(582, 93, 111, 101))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.carLogo.sizePolicy().hasHeightForWidth())
        self.carLogo.setSizePolicy(sizePolicy)
        self.carLogo.setObjectName("carLogo")

        self.enameTitle = QtWidgets.QLabel(Form)
        self.enameTitle.setGeometry(QtCore.QRect(700, 120, 72, 18))
        self.enameTitle.setObjectName("enameTitle")

        self.cnameTitle = QtWidgets.QLabel(Form)
        self.cnameTitle.setGeometry(QtCore.QRect(700, 147, 72, 18))
        self.cnameTitle.setObjectName("cnameTitle")

        self.introText = QtWidgets.QTextBrowser(Form)
        self.introText.setGeometry(QtCore.QRect(581, 248, 331, 300))
        self.introText.setObjectName("introText")

        self.introTitle = QtWidgets.QLabel(Form)
        self.introTitle.setGeometry(QtCore.QRect(580, 220, 72, 18))
        self.introTitle.setObjectName("introTitle")

        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(770, 550, 144, 18))
        self.label.setObjectName("label")

        self.ename = QtWidgets.QLabel(Form)
        self.ename.setGeometry(QtCore.QRect(780, 120, 81, 18))
        self.ename.setObjectName("ename")

        self.cname = QtWidgets.QLabel(Form)
        self.cname.setGeometry(QtCore.QRect(780, 147, 81, 18))
        self.cname.setObjectName("cname")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        Form.setObjectName("Form")

        Form.resize(981, 646)
        self.tableWidget = QtWidgets.QTableWidget(Form)
        # self.tableWidget = QTableWidget()
        self.tableWidget.setGeometry(QtCore.QRect(20, 100, 550, 450))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(12)
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setIconSize(QSize(180, 100))
        layout = QHBoxLayout()
        layout.addWidget(self.tableWidget)
        self.tableWidget.setHorizontalHeaderLabels(['外观', '车名', '评分', '级别', '发动机规格'])
        self.tableWidget.horizontalHeader().setStyleSheet(
            "QHeaderView::section{background-color:rgb(240,240,240);color: black;};")
        self.tableWidget.verticalHeader().setStyleSheet(
            "QHeaderView::section{background-color:rgb(240,240,240);color: black;};")

        item = []

        test = []
        url = []
        req = []
        lbp = []
        logo = []

        rate = []
        rank = []
        engine = []

        length = len(self.list)
        print(length)
        for i in range(length):
            if (len(self.list[i]) == 0):
                print(list)
                break


            item.append("item" + str(i))
            rate.append("rate" + str(i))
            rank.append("rank" + str(i))
            engine.append("engine" + str(i))

            item[i] = QTableWidgetItem(self.list[i][0])
            item[i].setBackground(QBrush(QColor(240, 240, 240)))
            item[i].setFlags(Qt.ItemIsSelectable | Qt.ItemIsEnabled)
            rate[i] = QTableWidgetItem(self.list[i][2])
            rate[i].setFlags(Qt.ItemIsSelectable | Qt.ItemIsEnabled)
            rate[i].setBackground(QBrush(QColor(240, 240, 240)))
            rank[i] = QTableWidgetItem(self.list[i][3])
            rank[i].setFlags(Qt.ItemIsSelectable | Qt.ItemIsEnabled)
            rank[i].setBackground(QBrush(QColor(240, 240, 240)))
            engine[i] = QTableWidgetItem(self.list[i][4])
            engine[i].setFlags(Qt.ItemIsSelectable | Qt.ItemIsEnabled)
            engine[i].setBackground(QBrush(QColor(240, 240, 240)))

            self.tableWidget.setItem(i, 1, item[i])
            self.tableWidget.setItem(i, 2, rate[i])
            self.tableWidget.setItem(i, 3, rank[i])
            self.tableWidget.setItem(i, 4, engine[i])
        # 实现单元格图文混排效果
        for i in range(length):
            if (len(self.list) == 0):
                print('self.list')
                break
            test.append("test" + str(i))
            url.append("url" + str(i))
            req.append("req" + str(i))
            lbp.append("lbp" + str(i))
            logo.append("logo" + str(i))
            url[i] = self.list[i][1]
            req[i] = requests.get(url[i])
            logo[i] = QtGui.QPixmap()
            logo[i].loadFromData(req[i].content)
            logo[i] = logo[i].scaled(QtCore.QSize(105, 80))

            lbp[i] = QLabel()
            lbp[i].setPixmap(logo[i])
            self.tableWidget.setCellWidget(i, 0, lbp[i])
            # 在表中添加一张图片
            twi = QTableWidgetItem("Graph")
            twi.setBackground(QBrush(QColor(240, 240, 240)))
            twi.setFont(QFont("Times", 10, ))
            self.tableWidget.setItem(i, 0, twi)

            self.tableWidget.setShowGrid(False)
            for i in range(4):
                self.tableWidget.setColumnWidth(i, 102)

            # 让行的高度和图片高度相同
            for i in range(12):
                self.tableWidget.setRowHeight(i, 100)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.enameTitle.setText(_translate("Form", "英文名："))
        self.enameTitle.adjustSize()
        self.cnameTitle.setText(_translate("Form", "中文名："))
        self.introTitle.setText(_translate("Form", "品牌介绍"))

        # print(self.brandInfo)
        self.ename.setText(_translate("Form", self.brandInfo[0]))  # 中文名
        self.ename.resize(len(self.brandInfo[0]) * 10, 18)

        self.cname.setText(_translate("Form", self.brandInfo[1]))  # 英文名
        # self.cname.resize(len(self.brandInfo[1])*20,18)

        self.introText.setText(_translate("Form", self.brandInfo[3]))  # 介绍

        self.label.setText(_translate("Form", '更详细内容请<a href="%s">点击</a>' % self.brandInfo[4]))
        self.label.setOpenExternalLinks(True)  # 使成为超链接，外部浏览器打开

        url = self.brandInfo[2]
        req = requests.get(url)
        logo = QtGui.QPixmap()
        logo.loadFromData(req.content)
        logo = logo.scaled(QtCore.QSize(80, 80))
        self.carLogo.setPixmap(logo)


if __name__ == '__main__':
    QtCore.QCoreApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling)
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QMainWindow()
    # showBrandIntro = Ui_BrandIntro(result) #传入识别结果
    # 可能是字符编码问题，下行可以，下下行不行
    # showBrandIntro = Ui_BrandIntro("Land Rover") #传入识别结果
    showBrandIntro = Ui_BrandIntro("Volvo")  # 传入识别结果
    showBrandIntro.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
