# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'left_table.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import requests
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QSize
from PyQt5.QtGui import QFont
from PyQt5.QtWidgets import QHBoxLayout, QTableWidgetItem, QLabel
from CarRecommendSpider import *

class Ui_Form(object):
    list = get_one_brand(70)
    print(list)

    def setupUi(self, Form):
        Form.setObjectName("Form")
        self.setWindowTitle("单元格中图文混排")
        Form.resize(981, 646)
        self.tableWidget = QtWidgets.QTableWidget(Form)
        # self.tableWidget = QTableWidget()
        self.tableWidget.setGeometry(QtCore.QRect(20, 120, 550, 500))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(12)
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setIconSize(QSize(180, 100))
        layout = QHBoxLayout()
        layout.addWidget(self.tableWidget)
        self.tableWidget.setHorizontalHeaderLabels(['外观','车名', '评分', '级别', '发动机规格'])
        item = []
        test = []
        url = []
        req = []
        lbp = []
        logo = []
        rate =[]
        rank =[]
        engine =[]

        length = len(self.list)
        print(length)
        for i in range(length):
            if (len(self.list[i])==0):
                break

            item.append("item" + str(i))
            rate.append("rate"+str(i))
            rank.append("rank" + str(i))
            engine.append("engine" + str(i))
            item[i] = QTableWidgetItem(self.list[i][0])
            rate[i]= QTableWidgetItem(self.list[i][2])
            rank[i]= QTableWidgetItem(self.list[i][3])
            engine[i] = QTableWidgetItem(self.list[i][4])

            self.tableWidget.setItem(i, 1, item[i])
            self.tableWidget.setItem(i, 2, rate[i])
            self.tableWidget.setItem(i, 3, rank[i])
            self.tableWidget.setItem(i, 4, engine[i])

        # 实现单元格图文混排效果
        for i in range(length):
            if (len(self.list[i]) == 0):
                break
            test.append("test" + str(i))
            url.append("url" + str(i))
            req.append("req" + str(i))
            lbp.append("lbp" + str(i))
            logo.append("logo" + str(i))
            # test[i] = QTableWidgetItem(QIcon("../picture/i.jpg"),str(""))
            url[i] = self.list[i][1]
            req[i] = requests.get(url[i])
            logo[i] = QtGui.QPixmap()
            logo[i].loadFromData(req[i].content)
            logo[i] = logo[i].scaled(QtCore.QSize(110, 80))

            lbp[i] = QLabel()
            lbp[i].setPixmap(logo[i])
            self.tableWidget.setCellWidget(i, 0, lbp[i])
            # 在表中添加一张图片
            twi = QTableWidgetItem("Graph")
            twi.setFont(QFont("Times", 10, ))
            self.tableWidget.setItem(i, 0, twi)



        # lbp = QLabel()
        # lbp.setPixmap(logo)
        # self.tableWidget.setCellWidget(1, 1, lbp)
        # # 在表中添加一张图片
        # twi = QTableWidgetItem("Graph")
        # twi.setFont(QFont("Times", 10, ))
        # self.tableWidget.setItem(1, 1, twi)
        #     # self.tableWidget.setItem(i, 1, test[i])
        # lbp1 = QLabel()
        # lbp1.setPixmap(QPixmap("../picture/2.jpg"))
        # self.tableWidget.setCellWidget(0, 1, lbp1)
        # # 在表中添加一张图片
        # twi1 = QTableWidgetItem("Graph1")
        # twi1.setFont(QFont("Times", 10, ))
        # self.tableWidget.setItem(0, 1, twi1)

        # 长
        self.tableWidget.setColumnWidth(0, 110)
        self.tableWidget.setColumnWidth(5, 40)
        for i in range(1,4):
            self.tableWidget.setColumnWidth(i, 98)
        # 高
        for i in range(12):
            self.tableWidget.setRowHeight(i, 100)
        self.setLayout(layout)
    #     Form.setObjectName("Form")
    #     Form.resize(400, 300)
    #     self.tableWidget = QtWidgets.QTableWidget(Form)
    #     self.tableWidget.setGeometry(QtCore.QRect(40, 20, 100, 120))
    #     self.tableWidget.setObjectName("tableWidget")
    #     self.tableWidget.setColumnCount(2)
    #     self.tableWidget.setRowCount(2)
    #     item = QtWidgets.QTableWidgetItem()
    #     self.tableWidget.setVerticalHeaderItem(0, item)
    #     item = QtWidgets.QTableWidgetItem()
    #     self.tableWidget.setVerticalHeaderItem(1, item)
    #     item = QtWidgets.QTableWidgetItem()
    #     self.tableWidget.setHorizontalHeaderItem(0, item)
    #     item = QtWidgets.QTableWidgetItem()
    #     self.tableWidget.setHorizontalHeaderItem(1, item)
    #
    #     self.retranslateUi(Form)
    #     QtCore.QMetaObject.connectSlotsByName(Form)
    #
    # def retranslateUi(self, Form):
    #     _translate = QtCore.QCoreApplication.translate
    #     Form.setWindowTitle(_translate("Form", "Form"))
    #     item = self.tableWidget.verticalHeaderItem(0)
    #     item.setText(_translate("Form", "新建行"))
    #     item = self.tableWidget.verticalHeaderItem(1)
    #     item.setText(_translate("Form", "新建行"))
    #     item = self.tableWidget.horizontalHeaderItem(0)
    #     item.setText(_translate("Form", "新建列"))
    #     item = self.tableWidget.horizontalHeaderItem(1)
    #     item.setText(_translate("Form", "新建列"))

